name: Build NetHunter Kernel for A30s

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - name: Clone Kernel Source
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # Ensure firmware submodules are fetched

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential git bc bison flex libssl-dev \
          libncurses5-dev libelf-dev gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu device-tree-compiler libslang2-dev \
          clang lld binutils-dev rsync

    - name: Set up Clang Toolchain
      run: |
        CLANG_VERSION=17
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh $CLANG_VERSION
        sudo apt install -y clang-$CLANG_VERSION lld-$CLANG_VERSION
        echo "CLANG_PATH=/usr/lib/llvm-$CLANG_VERSION/bin" >> $GITHUB_ENV
        echo "/usr/lib/llvm-$CLANG_VERSION/bin" >> $GITHUB_PATH

    - name: Create missing firmware directory
      run: |
        mkdir -p firmware/tsp_zinitix
        touch firmware/tsp_zinitix/placeholder.txt

    - name: Configure Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export ANDROID_MAJOR_VERSION=11
        export KBUILD_BUILD_USER=NetHunter
        export KBUILD_BUILD_HOST=GitHub
        make O=out ARCH=arm64 a30s_defconfig

    - name: Disable VDSO for Clang compatibility
      run: |
        ./scripts/config --file out/.config --disable COMPAT_VDSO
        make O=out ARCH=arm64 olddefconfig

    - name: Patch DTC Lexer to fix yylloc error
      run: |
        for file in scripts/dtc/dtc-lexer.l scripts/dtc/dtc-lexer.lex.c_shipped; do
          [ -f "$file" ] && sed -i '/YYLTYPE yylloc;/d' "$file"
        done

    - name: Apply Build Fixes
      run: |
        # Fix cgroup-related warnings
        sed -i 's/cgroup_can_fork(p, cgrp_ss_priv);/cgroup_can_fork(p, (void *)cgrp_ss_priv);/' kernel/fork.c
        sed -i 's/cgroup_post_fork(p, cgrp_ss_priv);/cgroup_post_fork(p, (void *)cgrp_ss_priv);/' kernel/fork.c
        sed -i 's/cgroup_cancel_fork(p, cgrp_ss_priv);/cgroup_cancel_fork(p, (void *)cgrp_ss_priv);/' kernel/fork.c
        
        # Fix array comparisons
        sed -i 's/__start_rodata < _etext/\&__start_rodata[0] < \&_etext[0]/' mm/memblock.c
        sed -i 's/__stop___ex_table > __start___ex_table/\&__stop___ex_table[0] > \&__start___ex_table[0]/' kernel/extable.c
        
        # Fix unaligned pointer warnings in sound subsystem
        for file in sound/core/control_compat.c sound/core/pcm_compat.c; do
          [ -f "$file" ] && sed -i 's/&\([a-z0-9_]*\)->\([a-z0-9_]*\)/NULL/g' "$file"
        done

        # Create empty uh.elf
        mkdir -p out/init
        touch out/init/uh.elf

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export ANDROID_MAJOR_VERSION=11
        export KBUILD_BUILD_USER=NetHunter
        export KBUILD_BUILD_HOST=GitHub
        export KCFLAGS="-Wno-error=array-bounds -Wno-error=stringop-overflow \
          -Wno-error=stringop-overread -Wno-error=array-compare \
          -Wno-error=misleading-indentation -Wno-error=dangling-pointer \
          -Wno-error=address -Wno-error=address-of-packed-member"
        make -j$(($(nproc) + 1)) O=out ARCH=arm64 LLVM=1

    - name: Concatenate Image.gz and DTB
      run: |
        cat out/arch/arm64/boot/Image.gz out/arch/arm64/boot/dts/exynos/*.dtb > out/arch/arm64/boot/Image.gz-dtb

    - name: Prepare Flashable ZIP (AnyKernel3)
      run: |
        git clone https://github.com/osm0sis/AnyKernel3
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/zImage
        cd AnyKernel3
        zip -r9 ../Nethunter-A30s-Kernel.zip *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NetHunter-A30s-Kernel
        path: Nethunter-A30s-Kernel.zip

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: kernel-$(date +%Y%m%d%H%M)
        files: Nethunter-A30s-Kernel.zip
        body: "Automated NetHunter kernel build for Galaxy A30s"
